const DELAY_TIME = 2000;
const LIVESTREAM_COUNTER_EXPIRED_TIME = process.env.LIVESTREAM_COUNTER_EXPIRED_TIME || 12 * 60 * 60;
const FIREBASE_SERVICE_ACCOUNT = process.env.FIREBASE_SERVICE_ACCOUNT || 'app-service-account-firebase.json';

/**
 *
 * @return {string}
 */
const getKeyFileName = () => {
	let KEY_FILENAME = `./app-service-account.json`;
	if (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') {
		KEY_FILENAME = `./${process.env.PATH_SERVICE_ACCOUNT_GCP}`;
	}
	return KEY_FILENAME;
}

const MIN_KEY_FORMAT = 'YYYYMMDDHHmm';
const SECOND_KEY_FORMAT = 'YYYYMMDDHHmmss';

const DURATION_COUNTING_CCU = process.env.DURATION_COUNTING_CCU || 10;
const DURATION_MERGE_CCU = process.env.DURATION_MERGE_CCU || 10000;

const CHAT_EVENT = process.env.CHAT_EVENT || 'CHAT_EVENT';

const PUBSUB = {
	SUBSCRIPTION: {
		LIVESTREAM_COUNTER_CCU: 'LIVESTREAM_COUNTER_CCU',
		LIVESTREAM_COMMAND: 'LIVESTREAM_COMMAND'
	},
	TOPIC: {
		VIDEO_WATCHED: 'VIDEO_WATCHED',
		CHAT_EVENT: 'CHAT_EVENT',
		SERVICE_NOTIFICATION: 'SERVICE_NOTIFICATION'
	}
}

const KEY_LIST_CONTENT = process.env.KEY_LIST_CONTENT || 'list_content';

module.exports = {
	DELAY_TIME: DELAY_TIME,
	KEY_FILENAME: getKeyFileName(),
	LIVESTREAM_COUNTER_EXPIRED_TIME: LIVESTREAM_COUNTER_EXPIRED_TIME,
	MIN_KEY_FORMAT: MIN_KEY_FORMAT,
	SECOND_KEY_FORMAT: SECOND_KEY_FORMAT,
	DURATION_COUNTING_CCU: DURATION_COUNTING_CCU,
	CHAT_EVENT: CHAT_EVENT,
	FIREBASE_SERVICE_ACCOUNT: FIREBASE_SERVICE_ACCOUNT,
	DURATION_MERGE_CCU: DURATION_MERGE_CCU,
	PUBSUB: PUBSUB,
	KEY_LIST_CONTENT: KEY_LIST_CONTENT
}
